# Generated by Django 5.0.3 on 2024-03-20 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="billingaddress",
            name="new_field",
            field=models.CharField(
                blank=True, default="SOME STRING", max_length=140, null=True
            ),
        ),
    ]
