// breakfast, lunch, dinner list
export const BREAKFAST_LIST_REQUEST = "BREAKFAST_LIST_REQUEST"
export const BREAKFAST_LIST_SUCCESS = "BREAKFAST_LIST_SUCCESS"
export const BREAKFAST_LIST_FAIL = "BREAKFAST_LIST_FAIL"

export const DINNER_LIST_REQUEST = "DINNER_LIST_REQUEST"
export const DINNER_LIST_SUCCESS = "DINNER_LIST_SUCCESS"
export const DINNER_LIST_FAIL = "DINNER_LIST_FAIL"

export const LUNCH_LIST_REQUEST = "LUNCH_LIST_REQUEST"
export const LUNCH_LIST_SUCCESS = "LUNCH_LIST_SUCCESS"
export const LUNCH_LIST_FAIL = "LUNCH_LIST_FAIL"

// breakfast, lunch, dinner details
export const BREAKFAST_DETAILS_REQUEST= "BREAKFAST_DETAILS_REQUEST"
export const BREAKFAST_DETAILS_SUCCESS= "BREAKFAST_DETAILS_SUCCESS"
export const BREAKFAST_DETAILS_FAIL= "BREAKFAST_DETAILS_FAIL"

export const LUNCH_DETAILS_REQUEST = "LUNCH_DETAILS_REQUEST"
export const LUNCH_DETAILS_SUCCESS = "LUNCH_DETAILS_SUCCESS"
export const LUNCH_DETAILS_FAIL = "LUNCH_DETAILS_FAIL"

export const DINNER_DETAILS_REQUEST = "DINNER_DETAILS_REQUEST"
export const DINNER_DETAILS_SUCCESS = "DINNER_DETAILS_SUCCESS"
export const DINNER_DETAILS_FAIL = "DINNER_DETAILS_FAIL"

// create Breakfast, Lunch and Dinner  Details
export const CREATE_BREAKFAST_REQUEST = "CREATE_BREAKFAST_REQUEST"
export const CREATE_BREAKFAST_SUCCESS = "CREATE_BREAKFAST_SUCCESS"
export const CREATE_BREAKFAST_FAIL = "CREATE_BREAKFAST_FAIL"
export const CREATE_BREAKFAST_RESET = "CREATE_BREAKFAST_RESET"

export const CREATE_LUNCH_REQUEST = "CREATE_LUNCH_REQUEST"
export const CREATE_LUNCH_SUCCESS = "CREATE_LUNCH_SUCCESS"
export const CREATE_LUNCH_FAIL = "CREATE_LUNCH_FAIL"
export const CREATE_LUNCH_RESET = "CREATE_LUNCH_RESET"

export const CREATE_DINNER_REQUEST = "CREATE_DINNER_REQUEST"
export const CREATE_DINNER_SUCCESS = "CREATE_DINNER_SUCCESS"
export const CREATE_DINNER_FAIL = "CREATE_DINNER_FAIL"
export const CREATE_DINNER_RESET = "CREATE_DINNER_RESET"

// update Breakfast, Lunch and Dinner Details
export const UPDATE_BREAKFAST_REQUEST= "UPDATE_BREAKFAST_REQUEST"
export const UPDATE_BREAKFAST_SUCCESS= "UPDATE_BREAKFAST_SUCCESS"
export const UPDATE_BREAKFAST_FAIL= "UPDATE_BREAKFAST_FAIL"
export const UPDATE_BREAKFAST_RESET= "UPDATE_BREAKFAST_RESET"

export const UPDATE_LUNCH_REQUEST = "UPDATE_LUNCH_REQUEST"
export const UPDATE_LUNCH_SUCCESS = "UPDATE_LUNCH_SUCCESS"
export const UPDATE_LUNCH_FAIL = "UPDATE_LUNCH_FAIL"
export const UPDATE_LUNCH_RESET = "UPDATE_LUNCH_RESET"

export const UPDATE_DINNER_REQUEST = "UPDATE_DINNER_REQUEST"
export const UPDATE_DINNER_SUCCESS = "UPDATE_DINNER_SUCCESS"
export const UPDATE_DINNER_FAIL = "UPDATE_DINNER_FAIL"
export const UPDATE_DINNER_RESET = "UPDATE_DINNER_RESET"

// delete Breakfast, Lunch, Dinner details
export const DELETE_BREAKFAST_REQUEST = "DELETE_BREAKFAST_REQUEST"
export const DELETE_BREAKFAST_SUCCESS = "DELETE_BREAKFAST_SUCCESS"
export const DELETE_BREAKFAST_FAIL = "DELETE_BREAKFAST_FAIL"
export const DELETE_BREAKFAST_RESET = "DELETE_BREAKFAST_RESET"

export const DELETE_LUNCH_RESET = "DELETE_LUNCH_RESET"
export const DELETE_LUNCH_SUCCESS = "DELETE_LUNCH_SUCCESS"
export const DELETE_LUNCH_FAIL = "DELETE_LUNCH_FAIL"
export const DELETE_LUNCH_REQUEST = "DELETE_LUNCH_REQUEST"

export const DELETE_DINNER_REQUEST = "DELETE_LUNCH_REQUEST"
export const DELETE_DINNER_SUCCESS = "DELETE_LUNCH_SUCCESS"
export const DELETE_DINNER_FAIL = "DELETE_LUNCH_FAIL"
export const DELETE_DINNER_RESET = "DELETE_LUNCH_RESET"

// check token validation
export const CHECK_TOKEN_VALID_REQUEST = "CHECK_TOKEN_VALID_REQUEST"
export const CHECK_TOKEN_VALID_SUCCESS = "CHECK_TOKEN_VALID_SUCCESS"
export const CHECK_TOKEN_VALID_FAIL = "CHECK_TOKEN_VALID_FAIL"
export const CHECK_TOKEN_VALID_RESET = "CHECK_TOKEN_VALID_RESET"
// user login/logout
export const USER_LOGIN_REQUEST = "USER_LOGIN_REQUEST"
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS"
export const USER_LOGIN_FAIL = "USER_LOGIN_FAIL"
export const USER_LOGOUT = "USER_LOGOUT"

// user registration/signup
export const USER_REGISTER_REQUEST = "USER_REGISTER_REQUEST"
export const USER_REGISTER_SUCCESS = "USER_REGISTER_SUCCESS"
export const USER_REGISTER_FAIL = "USER_REGISTER_FAIL"

// user info/details
export const USER_DETAILS_REQUEST = "USER_DETAILS_REQUEST"
export const USER_DETAILS_SUCCESS = "USER_DETAILS_SUCCESS"
export const USER_DETAILS_FAIL = "USER_DETAILS_FAIL"

// user update details
export const UPDATE_USER_DETAILS_REQUEST = "UPDATE_USER_DETAILS_REQUEST"
export const UPDATE_USER_DETAILS_SUCCESS = "UPDATE_USER_DETAILS_SUCCESS"
export const UPDATE_USER_DETAILS_FAIL = "UPDATE_USER_DETAILS_FAIL"
export const UPDATE_USER_DETAILS_RESET = "UPDATE_USER_DETAILS_RESET"

// delete user account
export const DELETE_USER_ACCOUNT_REQUEST = "DELETE_USER_ACCOUNT_REQUEST" 
export const DELETE_USER_ACCOUNT_SUCCESS = "DELETE_USER_ACCOUNT_SUCCESS" 
export const DELETE_USER_ACCOUNT_FAIL = "DELETE_USER_ACCOUNT_FAIL" 
export const DELETE_USER_ACCOUNT_RESET = "DELETE_USER_ACCOUNT_RESET" 

// user all address
export const GET_USER_ALL_ADDRESSES_REQUEST = "GET_USER_ALL_ADDRESSES_REQUEST"
export const GET_USER_ALL_ADDRESSES_SUCCESS = "GET_USER_ALL_ADDRESSES_SUCCESS"
export const GET_USER_ALL_ADDRESSES_FAIL = "GET_USER_ALL_ADDRESSES_FAIL"

// user single address details
export const GET_SINGLE_ADDRESS_REQUEST = "GET_SINGLE_ADDRESS_REQUEST"
export const GET_SINGLE_ADDRESS_SUCCESS = "GET_SINGLE_ADDRESS_SUCCESS"
export const GET_SINGLE_ADDRESS_FAIL = "GET_SINGLE_ADDRESS_FAIL"
export const GET_SINGLE_ADDRESS_RESET = "GET_SINGLE_ADDRESS_RESET"

// create address
export const CREATE_USER_ADDRESS_REQUEST = "CREATE_USER_ADDRESS_REQUEST"
export const CREATE_USER_ADDRESS_SUCCESS = "CREATE_USER_ADDRESS_SUCCESS"
export const CREATE_USER_ADDRESS_FAIL = "CREATE_USER_ADDRESS_FAIL"
export const CREATE_USER_ADDRESS_RESET = "CREATE_USER_ADDRESS_RESET"

// update address
export const UPDATE_USER_ADDRESS_REQUEST = "UPDATE_USER_ADDRESS_REQUEST"
export const UPDATE_USER_ADDRESS_SUCCESS = "UPDATE_USER_ADDRESS_SUCCESS"
export const UPDATE_USER_ADDRESS_FAIL = "UPDATE_USER_ADDRESS_FAIL"
export const UPDATE_USER_ADDRESS_RESET = "UPDATE_USER_ADDRESS_RESET"

// delete user address
export const DELETE_USER_ADDRESS_REQUEST = "DELETE_USER_ADDRESS_REQUEST"
export const DELETE_USER_ADDRESS_SUCCESS = "DELETE_USER_ADDRESS_SUCCESS"
export const DELETE_USER_ADDRESS_FAIL = "DELETE_USER_ADDRESS_FAIL"
export const DELETE_USER_ADDRESS_RESET = "DELETE_USER_ADDRESS_RESET"

// all orders list
export const GET_ALL_ORDERS_REQUEST = "GET_ALL_ORDERS_REQUEST"
export const GET_ALL_ORDERS_SUCCESS = "GET_ALL_ORDERS_SUCCESS"
export const GET_ALL_ORDERS_FAIL = "GET_ALL_ORDERS_FAIL"

// change order delivery status
export const CHANGE_DELIVERY_STATUS_REQUEST = "CHANGE_DELIVERY_STATUS_REQUEST"
export const CHANGE_DELIVERY_STATUS_SUCCESS = "CHANGE_DELIVERY_STATUS_SUCCESS"
export const CHANGE_DELIVERY_STATUS_FAIL = "CHANGE_DELIVERY_STATUS_FAIL"
export const CHANGE_DELIVERY_STATUS_RESET = "CHANGE_DELIVERY_STATUS_RESET"

// create mpesa transaction
export const MPESA_TRANSACTION_RESET = "MPESA_CREATE_RESET"

// STK push status
export const MPESA_STK_PUSH_REQUEST = "MPESA_STK_PUSH_REQUEST"
export const MPESA_STK_PUSH_FAIL = "MPESA_STK_PUSH_FAIL"
export const MPESA_STK_PUSH_SUCCESS = "MPESA_STK_PUSH_SUCCESS"

// call-back handler status
export const MPESA_CALLBACK_HANDLER_REQUEST = "MPESA_CALLBACK_HANDLER_REQUEST"
export const MPESA_CALLBACK_HANDLER_FAIL = "MPESA_CALLBACK_HANDLER_FAIL"
export const MPESA_CALLBACK_HANDLER_SUCCESS = "MPESA_CALLBACK_HANDLER_SUCCESS"

// add-to-cart status
export const ADD_TO_CART_REQUEST = "ADD_TO_CART_REQUEST"
export const ADD_TO_CART_SUCCESS = "ADD_TO_CART_SUCCESS"
export const ADD_TO_CART_FAIL = "ADD_TO_CART_FAIL"
export const ADD_TO_CART_RESET = "ADD_TO_CART_RESET"

// remove-from-cart status
export const REMOVE_FROM_CART_REQUEST= "REMOVE_FROM_CART_REQUEST"
export const REMOVE_FROM_CART_SUCCESS= "REMOVE_FROM_CART_SUCCESS"
export const REMOVE_FROM_CART_FAIL= "REMOVE_FROM_CART_FAIL"

// Loop from cart database
export const LOOP_FROM_CART_DATABASE_REQUEST= "LOOP_FROM_CART_DATABASE_REQUEST"
export const LOOP_FROM_CART_DATABASE_SUCCESS= "LOOP_FROM_CART_DATABASE_SUCCESS"
export const LOOP_FROM_CART_DATABASE_FAIL= "LOOP_FROM_CART_DATABASE_FAIL"

// Total-price
export const GET_TOTAL_PRICE_REQUEST="GET_TOTAL_PRICE_REQUEST"
export const GET_TOTAL_PRICE_SUCCESS="GET_TOTAL_PRICE_SUCCESS"
export const GET_TOTAL_PRICE_FAIL="GET_TOTAL_PRICE_FAIL"




